#                                                           Developed by Vasty
#                                                     (Aquatic Studios @ (C) 2016-2025)

name: AuthCore
version: '1.0'
authors: [Vasty]

main: dev.club.aquatic.AuthCore
api-version: '1.20'
website: https://github.com/aquaticstudios